/**
 * @file server.js
 * @brief Multi-AI Code Review Orchestrator
 *
 * 2026 Best Practice: Layer multiple specialized AIs
 * - General Review: Claude/GPT for logic and readability
 * - Security Focus: Snyk/Aikido for vulnerabilities
 * - Performance: CodeGuru for optimizations
 */

const express = require('express');
const crypto = require('crypto');
const { Octokit } = require('@octokit/rest');

const app = express();
app.use(express.json());

// GitHub client for posting comments
const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

// Webhook secret validation
const WEBHOOK_SECRET = process.env.WEBHOOK_SECRET;

function verifySignature(req) {
    const signature = req.headers['x-hub-signature-256'];
    const hmac = crypto.createHmac('sha256', WEBHOOK_SECRET);
    const digest = 'sha256=' + hmac.update(JSON.stringify(req.body)).digest('hex');
    return crypto.timingSafeEqual(Buffer.from(signature), Buffer.from(digest));
}

// AI Review Functions
async function generalReview(diff) {
    // Claude API for logic and readability
    const response = await fetch('https://api.anthropic.com/v1/messages', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'x-api-key': process.env.ANTHROPIC_API_KEY,
            'anthropic-version': '2023-06-01'
        },
        body: JSON.stringify({
            model: 'claude-sonnet-4-20250514',
            max_tokens: 2000,
            messages: [{
                role: 'user',
                content: `Review this code diff for:
1. Logic errors and bugs
2. Code readability and maintainability
3. Best practices violations
4. Potential edge cases

Respond in JSON format with: { "issues": [...], "suggestions": [...] }

Diff:
${diff}`
            }]
        })
    });
    return response.json();
}

async function securityReview(diff) {
    // Security-focused review
    const response = await fetch('https://api.anthropic.com/v1/messages', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'x-api-key': process.env.ANTHROPIC_API_KEY,
            'anthropic-version': '2023-06-01'
        },
        body: JSON.stringify({
            model: 'claude-sonnet-4-20250514',
            max_tokens: 2000,
            messages: [{
                role: 'user',
                content: `SECURITY REVIEW - Check for:
1. OWASP Top 10 vulnerabilities
2. SQL injection, XSS, CSRF
3. Hardcoded secrets or credentials
4. Insecure cryptographic practices
5. Authentication/Authorization flaws

Rate each issue: Critical, High, Medium, Low

Diff:
${diff}`
            }]
        })
    });
    return response.json();
}

async function testCoverageReview(diff) {
    // Test suggestions
    const response = await fetch('https://api.anthropic.com/v1/messages', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'x-api-key': process.env.ANTHROPIC_API_KEY,
            'anthropic-version': '2023-06-01'
        },
        body: JSON.stringify({
            model: 'claude-sonnet-4-20250514',
            max_tokens: 2000,
            messages: [{
                role: 'user',
                content: `TEST COVERAGE REVIEW:
1. What test cases are missing?
2. What edge cases should be tested?
3. Suggest specific test implementations

Diff:
${diff}`
            }]
        })
    });
    return response.json();
}

// Consolidate and format feedback
function formatReviewComment(generalResult, securityResult, testResult) {
    return `## AI Code Review Summary

### General Review
${generalResult.content[0].text}

### Security Review
${securityResult.content[0].text}

### Test Coverage
${testResult.content[0].text}

---
*This review was generated by Multi-AI Orchestrator. Treat as non-blocking suggestions.*
*Human reviewer should verify AI reasoning before approval.*`;
}

// Main webhook handler
app.post('/webhook/pr-review', async (req, res) => {
    // Validate webhook signature
    if (!verifySignature(req)) {
        return res.status(401).send('Invalid signature');
    }

    const { action, pull_request, repository } = req.body;

    // Only process opened or synchronized PRs
    if (!['opened', 'synchronize'].includes(action)) {
        return res.status(200).send('Ignored event');
    }

    try {
        // Get PR diff
        const diffResponse = await octokit.pulls.get({
            owner: repository.owner.login,
            repo: repository.name,
            pull_number: pull_request.number,
            mediaType: { format: 'diff' }
        });
        const diff = diffResponse.data;

        // Run multiple AI reviews in parallel
        const [generalResult, securityResult, testResult] = await Promise.all([
            generalReview(diff),
            securityReview(diff),
            testCoverageReview(diff)
        ]);

        // Post consolidated comment
        const comment = formatReviewComment(generalResult, securityResult, testResult);

        await octokit.issues.createComment({
            owner: repository.owner.login,
            repo: repository.name,
            issue_number: pull_request.number,
            body: comment
        });

        res.status(200).send('Review posted');
    } catch (error) {
        console.error('Review failed:', error);
        res.status(500).send('Review failed');
    }
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
    console.log(`AI Review Orchestrator running on port ${PORT}`);
});
